from enum import Enum


class EntityType(str, Enum):
    """Grocy entity type identifiers for the generic CRUD API."""

    BATTERIES = "batteries"
    BATTERY_CHARGE_CYCLES = "battery_charge_cycles"
    CHORES = "chores"
    CHORES_LOG = "chores_log"
    EQUIPMENT = "equipment"
    LOCATIONS = "locations"
    MEAL_PLAN = "meal_plan"
    MEAL_PLAN_SECTIONS = "meal_plan_sections"
    PERMISSION_HIERARCHY = "permission_hierarchy"
    PRODUCT_BARCODES = "product_barcodes"
    PRODUCT_BARCODES_VIEW = "product_barcodes_view"
    PRODUCT_GROUPS = "product_groups"
    PRODUCTS = "products"
    PRODUCTS_AVERAGE_PRICE = "products_average_price"
    PRODUCTS_LAST_PURCHASED = "products_last_purchased"
    QUANTITY_UNIT_CONVERSIONS = "quantity_unit_conversions"
    QUANTITY_UNIT_CONVERSIONS_RESOLVED = "quantity_unit_conversions_resolved"
    QUANTITY_UNITS = "quantity_units"
    RECIPES = "recipes"
    RECIPES_NESTINGS = "recipes_nestings"
    RECIPES_POS = "recipes_pos"
    RECIPES_POS_RESOLVED = "recipes_pos_resolved"
    SHOPPING_LIST = "shopping_list"
    SHOPPING_LISTS = "shopping_lists"
    SHOPPING_LOCATIONS = "shopping_locations"
    STOCK = "stock"
    STOCK_CURRENT_LOCATIONS = "stock_current_locations"
    STOCK_LOG = "stock_log"
    TASK_CATEGORIES = "task_categories"
    TASKS = "tasks"
    USERENTITIES = "userentities"
    USERFIELDS = "userfields"
    USEROBJECTS = "userobjects"
